# Generated by Django 3.0.3 on 2020-05-26 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poll_app', '0002_auto_20200526_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=0)),
                ('option', models.ForeignKey(max_length=264, on_delete=django.db.models.deletion.CASCADE, to='poll_app.Question')),
            ],
        ),
    ]
