# Generated by Django 3.0.3 on 2020-05-26 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0003_options_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Options',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
