# Generated by Django 3.0.3 on 2020-05-27 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0005_options_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='question',
            field=models.ForeignKey(max_length=264, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='poll_app.Question'),
        ),
    ]
